import { MigrationInterface, QueryRunner } from "typeorm"
import { v4 as uuidv4 } from "uuid";


export class DeliveryLocations1704196716004 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        const data = {
            district: "Chennai",
            values: [{ "area": "Abiramapuram", "pincode": "600018" },
            { "area": "Adyar", "pincode": "600020" },
            { "area": "Agaram", "pincode": "600082" },
            { "area": "Aminjikarai", "pincode": "600029" },
            { "area": "Anna Nagar", "pincode": "600040" },
            { "area": "Anna Nagar east", "pincode": "600102" },
            { "area": "Anna Nagar western extn", "pincode": "600101" },
            { "area": "Anna Road", "pincode": "600002" },
            { "area": "Arumbakkam", "pincode": "600106" },
            { "area": "Ashoknagar", "pincode": "600083" },
            { "area": "Aynavaram", "pincode": "600023" },
            { "area": "Besantnagar", "pincode": "600090" },
            { "area": "Broadway", "pincode": "600108" },
            { "area": "Cemetry Road", "pincode": "600021" },
            { "area": "Central Institute of technolog", "pincode": "600113" },
            { "area": "Central Leather research insti", "pincode": "600020" },
            { "area": "Chamiers Road", "pincode": "600018" },
            { "area": "Chennai Race course", "pincode": "600032" },
            { "area": "Chennai.", "pincode": "600001" },
            { "area": "Chepauk", "pincode": "600005" },
            { "area": "Chetput", "pincode": "600031" },
            { "area": "Chintadripet", "pincode": "600002" },
            { "area": "Choolai", "pincode": "600112" },
            { "area": "Choolaimedu", "pincode": "600094" },
            { "area": "D G vaishnav college", "pincode": "600106" },
            { "area": "Decosters Road", "pincode": "600012" },
            { "area": "Defence Officers colony", "pincode": "600032" },
            { "area": "Directorate Of tech education", "pincode": "600025" },
            { "area": "Dr. ambedkar nagar", "pincode": "600003" },
            { "area": "Edapalayam", "pincode": "600003" },
            { "area": "Egmore", "pincode": "600008" },
            { "area": "Ekkaduthangal", "pincode": "600032" },
            { "area": "Eldams Road", "pincode": "600018" },
            { "area": "Engineering College", "pincode": "600025" },
            { "area": "Erukkancheri", "pincode": "600118" },
            { "area": "Ethiraj Salai", "pincode": "600008" },
            { "area": "Flowers Road", "pincode": "600084" },
            { "area": "Foreshore Estate", "pincode": "600028" },
            { "area": "Fort St george", "pincode": "600009" },
            { "area": "G K m colony", "pincode": "600082" },
            { "area": "Gaudiyamath Road", "pincode": "600014" },
            { "area": "Golluvar Agraharam road", "pincode": "600021" },
            { "area": "Gopalapuram", "pincode": "600086" },
            { "area": "Government Estate", "pincode": "600002" },
            { "area": "Govt Stanley hospital", "pincode": "600001" },
            { "area": "Greams Road", "pincode": "600006" },
            { "area": "Guindy Industrial estate", "pincode": "600032" },
            { "area": "Guindy North", "pincode": "600015" },
            { "area": "High Court building", "pincode": "600104" },
            { "area": "Hindi Prachar sabha", "pincode": "600017" },
            { "area": "Icf Colony", "pincode": "600038" },
            { "area": "Indian Institute of technology", "pincode": "600036" },
            { "area": "Indira Nagar", "pincode": "600020" },
            { "area": "Jafferkhanpet", "pincode": "600083" },
            { "area": "Jam Bazaar", "pincode": "600014" },
            { "area": "Jawahar Nagar", "pincode": "600082" },
            { "area": "Kalaignar Karunanidhi nagar", "pincode": "600078" },
            { "area": "Kalmandapam", "pincode": "600013" },
            { "area": "Kasturibai Nagar", "pincode": "600020" },
            { "area": "Kdm West(mer with kdm)", "pincode": "600024" },
            { "area": "Kilpauk", "pincode": "600010" },
            { "area": "Kilpauk Medical college", "pincode": "600010" },
            { "area": "Kodambakkam", "pincode": "600024" },
            { "area": "Kodungaiyur", "pincode": "600118" },
            { "area": "Korrukupet", "pincode": "600021" },
            { "area": "Kosapet", "pincode": "600012" },
            { "area": "Kotturpuram", "pincode": "600085" },
            { "area": "Koyambedu", "pincode": "600107" },
            { "area": "Koyambedu Wholesale market com", "pincode": "600092" },
            { "area": "Krishnampet", "pincode": "600005" },
            { "area": "Kumaran Nagar", "pincode": "600033" },
            { "area": "Lloyds Estate", "pincode": "600014" },
            { "area": "Loyola College", "pincode": "600034" },
            { "area": "Mpt Ao", "pincode": "600001" },
            { "area": "Madras Electricity system", "pincode": "600002" },
            { "area": "Madras Medical college", "pincode": "600003" },
            { "area": "Madras Presidency college", "pincode": "600005" },
            { "area": "Madras University", "pincode": "600005" },
            { "area": "Mambalam R.s.", "pincode": "600033" },
            { "area": "Mandaveli", "pincode": "600004" },
            { "area": "Mannady", "pincode": "600001" },
            { "area": "Mettupalayam(mer With west mam", "pincode": "600033" },
            { "area": "Mint Building", "pincode": "600079" },
            { "area": "Muthialpet(ms)", "pincode": "600001" },
            { "area": "Mylapore", "pincode": "600004" },
            { "area": "Nandanam", "pincode": "600035" },
            { "area": "Nerkundram", "pincode": "600107" },
            { "area": "New Avadi road", "pincode": "600010" },
            { "area": "Nungambakkam", "pincode": "600034" },
            { "area": "Nungambakkam Bazaar", "pincode": "600034" },
            { "area": "Nungambakkam High road", "pincode": "600034" },
            { "area": "Old College buildings", "pincode": "600006" },
            { "area": "P C hostel", "pincode": "600030" },
            { "area": "Park Town", "pincode": "600003" },
            { "area": "Parthasarathy Koil", "pincode": "600005" },
            { "area": "Perambur", "pincode": "600011" },
            { "area": "Perambur Barracks", "pincode": "600012" },
            { "area": "Perambur High road", "pincode": "600012" },
            { "area": "Perambur North", "pincode": "600011" },
            { "area": "Pr. accountatn general", "pincode": "600018" },
            { "area": "Pudupakkam", "pincode": "600014" },
            { "area": "Pudupet", "pincode": "600002" },
            { "area": "Puliyanthope", "pincode": "600012" },
            { "area": "Purasawalkam", "pincode": "600084" },
            { "area": "Raja Annamalaipuram", "pincode": "600028" },
            { "area": "Rajathottam", "pincode": "600082" },
            { "area": "Rajbhavan", "pincode": "600022" },
            { "area": "Ramakrishna Nagar", "pincode": "600028" },
            { "area": "Rangarajapuram", "pincode": "600024" },
            { "area": "Rayapuram", "pincode": "600013" },
            { "area": "Ripon Buildings", "pincode": "600003" },
            { "area": "Royapettah", "pincode": "600014" },
            { "area": "Royapettah High road", "pincode": "600004" },
            { "area": "Royapuram Market", "pincode": "600013" },
            { "area": "Rv Nagar", "pincode": "600118" },
            { "area": "Saidapet", "pincode": "600015" },
            { "area": "Saidapet North", "pincode": "600015" },
            { "area": "Saidapet West(mer with sdp)", "pincode": "600015" },
            { "area": "Saligramam", "pincode": "600093" },
            { "area": "Santhome", "pincode": "600004" },
            { "area": "Sembiam", "pincode": "600011" },
            { "area": "Seven Wells", "pincode": "600001" },
            { "area": "Shastri Bhavan", "pincode": "600006" },
            { "area": "Shastri Nagar", "pincode": "600020" },
            { "area": "Shenoy Nagar", "pincode": "600030" },
            { "area": "Sowcarpet", "pincode": "600079" },
            { "area": "Sri Ayyappa nagar", "pincode": "600092" },
            { "area": "Strahans Road", "pincode": "600012" },
            { "area": "Teynampet", "pincode": "600018" },
            { "area": "Teynampet South", "pincode": "600018" },
            { "area": "Teynampet West", "pincode": "600006" },
            { "area": "Theosophical Society", "pincode": "600020" },
            { "area": "Thygaraya Nagar", "pincode": "600017" },
            { "area": "Thygaraya Nagar north", "pincode": "600017" },
            { "area": "Thygaraya Nagar south", "pincode": "600017" },
            { "area": "Tidel Park", "pincode": "600113" },
            { "area": "Tiruvallikkeni", "pincode": "600005" },
            { "area": "Tiruvanmiyur", "pincode": "600041" },
            { "area": "Tiruvanmiyur North", "pincode": "600041" },
            { "area": "Tondiarpet", "pincode": "600081" },
            { "area": "Tondiarpet Bazaar", "pincode": "600081" },
            { "area": "Tondiarpet West", "pincode": "600081" },
            { "area": "Triplicane South", "pincode": "600014" },
            { "area": "Ttti Taramani", "pincode": "600113" },
            { "area": "Vadapalani", "pincode": "600026" },
            { "area": "Velacheri", "pincode": "600042" },
            { "area": "Venkatesapuram", "pincode": "600012" },
            { "area": "Vepery", "pincode": "600007" },
            { "area": "Virugambakkam", "pincode": "600092" },
            { "area": "Vivekananda College madras", "pincode": "600004" },
            { "area": "Vyasar Nagar colony", "pincode": "600039" },
            { "area": "Vyasarpadi", "pincode": "600039" },
            { "area": "Washermanpet", "pincode": "600021" },
            { "area": "Washermanpet East", "pincode": "600021" },
            { "area": "West Mambalam", "pincode": "600033" },
            { "area": "World University centre", "pincode": "600031" },]

        };
        await queryRunner.query(`CREATE TABLE "delivery_locations" (
            "id" VARCHAR PRIMARY KEY,
            "area" VARCHAR NOT NULL,
            "pincode" VARCHAR NOT NULL,
            "district" VARCHAR NOT NULL,
            "selected_areas" BOOLEAN DEFAULT FALSE
        )`);
    
        for (const { area, pincode } of data.values) {
          const id = `dl_${uuidv4()}`; // Generates a UUID and prepends "pin_"
          const query = `
            INSERT INTO delivery_locations (id, area, pincode, district)
            VALUES ('${id}', '${area}', '${pincode}', '${data.district}')
          `;
          await queryRunner.query(query);
        }
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "pincodes"`);
    }

}
